version: "3.2"

services:
        mysql:
                build:
                        context: .
                        dockerfile: Dockerfile-mysql
                container_name: mysql
                ports:
                        - "3306:3306"
                volumes:
                        - mysql_data:/var/lib/mysql
                        
        api:
                build:
                        context: .
                        dockerfile: Dockerfile-api
                container_name: api
                ports:
                        - "3000:3000"
                volumes:
                        - ./api:/api
                depends_on:
                        - "mysql"

volumes:
        mysql_data: {}
